[package]
name = "n-puzzle"
version = "0.1.0"
edition = "2018"

[features]
use_move = []

[dependencies]
nom = "7.0.0"
ahash = "0.7.5"
clap = "3.0.0-beta.4"
pancurses = "0.17.0"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"
rand = "0.8.4"
clap-num = "0.2.0"
