[package]
name = "n-puzzle"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.8.0"
nom = "7.0.0"
ahash = "0.7.5"
